#!/usr/bin/env python3
"""
Setup script for Web MIDI Streamer
Creates config.php and chimes.json from example files
"""

import os
import shutil
import sys
from pathlib import Path


def prompt_with_default(message, default=""):
    """Prompt user with a default value"""
    if default:
        response = input(f"{message} [{default}]: ").strip()
        return response if response else default
    else:
        response = input(f"{message}: ").strip()
        return response


def prompt_yes_no(message, default=True):
    """Prompt user with yes/no question"""
    default_str = "Y/n" if default else "y/N"
    response = input(f"{message} [{default_str}]: ").strip().lower()
    if not response:
        return default
    return response in ['y', 'yes']


def setup_config_php():
    """Create config.php from user input"""
    print("\n=== TURN Server Configuration ===")
    print("This configures the TURN server for WebRTC connectivity.")
    print("Leave fields empty to use defaults.\n")
    
    # Prompt for configuration values
    turn_server = prompt_with_default(
        "TURN server domain", 
        "voice.denizsincar.ru"
    )
    
    print("\nTIP: Generate a secret with: openssl rand -base64 32")
    turn_secret = prompt_with_default(
        "TURN static-auth-secret",
        "YOUR_STATIC_AUTH_SECRET_HERE"
    )
    
    ttl = prompt_with_default(
        "Credential TTL in seconds",
        "3600"
    )
    
    print("\nCORS allowed origins:")
    print("  - Enter '*' for development (allows all origins)")
    print("  - Enter comma-separated domains for production")
    print("    Example: https://yourdomain.com,https://www.yourdomain.com")
    
    allowed_origins_input = prompt_with_default(
        "Allowed origins",
        "*"
    )
    
    # Parse allowed origins
    if allowed_origins_input == "*":
        allowed_origins = ["*"]
    else:
        allowed_origins = [origin.strip() for origin in allowed_origins_input.split(",")]
    
    # Format allowed origins for PHP array
    origins_php = ",\n        ".join([f"'{origin}'" for origin in allowed_origins])
    
    # Create config.php content
    config_content = f"""<?php
/**
 * TURN Server Configuration
 * 
 * Generated by setup.py
 * This file is gitignored to keep your secrets private.
 */

return [
    // Your TURN server domain
    'turnServer' => '{turn_server}',
    
    // Your static-auth-secret from /etc/turnserver.conf
    // Generate with: openssl rand -base64 32
    'turnSecret' => '{turn_secret}',
    
    // Credential TTL (time to live) in seconds
    'ttl' => {ttl},
    
    // Allowed origins for CORS
    'allowedOrigins' => [
        {origins_php}
    ],
];
"""
    
    # Write config.php
    config_path = Path("config.php")
    
    if config_path.exists():
        overwrite = prompt_yes_no(
            "\nconfig.php already exists. Overwrite?",
            default=False
        )
        if not overwrite:
            print("Skipping config.php creation.")
            return False
    
    with open(config_path, "w") as f:
        f.write(config_content)
    
    print(f"\n✅ Created config.php")
    return True


def setup_chimes_json():
    """Copy chimes.example.json to chimes.json"""
    print("\n=== MIDI Chimes Configuration ===")
    
    example_path = Path("chimes.example.json")
    target_path = Path("chimes.json")
    
    if not example_path.exists():
        print("❌ Error: chimes.example.json not found!")
        return False
    
    if target_path.exists():
        overwrite = prompt_yes_no(
            "chimes.json already exists. Overwrite?",
            default=False
        )
        if not overwrite:
            print("Skipping chimes.json creation.")
            return False
    
    # Copy the example file
    shutil.copy2(example_path, target_path)
    print(f"✅ Created chimes.json from chimes.example.json")
    print("   You can customize MIDI chimes by editing chimes.json")
    return True


def setup_signaling_directory():
    """Create signaling_data directory if it doesn't exist"""
    print("\n=== Signaling Server Setup ===")
    
    signaling_dir = Path("signaling_data")
    
    if not signaling_dir.exists():
        signaling_dir.mkdir(mode=0o755)
        print(f"✅ Created signaling_data/ directory")
    else:
        print("✅ signaling_data/ directory already exists")
    
    return True


def main():
    """Main setup function"""
    print("=" * 60)
    print("Web MIDI Streamer - Setup Script")
    print("=" * 60)
    print("\nThis script will help you set up the application.")
    print("It will create:")
    print("  - config.php (TURN server configuration)")
    print("  - chimes.json (MIDI chimes configuration)")
    print("  - signaling_data/ (signaling server data directory)")
    
    proceed = prompt_yes_no("\nProceed with setup?", default=True)
    if not proceed:
        print("\nSetup cancelled.")
        sys.exit(0)
    
    # Run setup steps
    success = True
    success = setup_config_php() and success
    success = setup_chimes_json() and success
    success = setup_signaling_directory() and success
    
    if success:
        print("\n" + "=" * 60)
        print("✅ Setup completed successfully!")
        print("=" * 60)
        print("\nNext steps:")
        print("  1. Review and edit config.php if needed")
        print("  2. Customize chimes.json if desired")
        print("  3. Start the server: php -S localhost:8080")
        print("  4. Open http://localhost:8080 in your browser")
    else:
        print("\n⚠️  Setup completed with some warnings.")
        print("Please review the output above.")
    
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)
